DROP SEQUENCE SEQ_Log;
DROP TABLE USERS;
DROP TABLE LOG_TABLE;

/* Sequence to register log (Primary Key) */
CREATE SEQUENCE SEQ_Log START WITH 1 INCREMENT BY 1;

/* Table Users */
CREATE TABLE USERS (
    ID_USER CHAR(16) NOT NULL, -- 'U_' || ID_LIDER
    PASSWORD CHAR(32) NOT NULL,
    ID_LIDER NOT NULL,
    CONSTRAINT PK_USERS PRIMARY KEY (ID_USER),
    CONSTRAINT FK_USER_LIDER FOREIGN KEY (ID_LIDER)
        REFERENCES LIDER(CPI) ON DELETE CASCADE
);

-- Table log
CREATE TABLE LOG_TABLE (
    ID_LOG VARCHAR(20),
    USERID CHAR(16) NOT NULL,
    TIMESTAMP TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    MESSAGE VARCHAR2(4000) NOT NULL,
    
    CONSTRAINT PK_LOG_TABELA_ESTRELA PRIMARY KEY (ID_LOG)
);