/* Table Users */
CREATE TABLE USERS (
    ID_USER CHAR(16) NOT NULL, -- 'U_' || ID_LIDER
    PASSWORD CHAR(32) NOT NULL,
    ID_LIDER NOT NULL,
    CONSTRAINT PK_USERS PRIMARY KEY (ID_USER),
    CONSTRAINT FK_USER_LIDER FOREIGN KEY (ID_LIDER)
        REFERENCES LIDER(CPI) ON DELETE CASCADE
);
-- DROP TABLE USERS;