CREATE OR REPLACE FUNCTION leaderReport ( p_faccao FACCAO.NOME%TYPE ) RETURN sys_refcursor IS
	c_report sys_refcursor;
BEGIN 
	OPEN c_report FOR
		SELECT p.FACCAO, c.NOME, c.ESPECIE, c.QTD_HABITANTES, h.PLANETA, d.NACAO, e.ID_ESTRELA, s.NOME 
			FROM participa p JOIN COMUNIDADE c ON p.COMUNIDADE = c.NOME AND p.ESPECIE = c.ESPECIE
			JOIN HABITACAO h ON h.COMUNIDADE = c.NOME AND h.ESPECIE = c.ESPECIE 
			JOIN DOMINANCIA d ON d.PLANETA = h.PLANETA
			JOIN ORBITA_PLANETA op ON op.PLANETA = h.PLANETA 
			JOIN ESTRELA e ON e.ID_ESTRELA = op.ESTRELA
			JOIN SISTEMA s ON s.ESTRELA = e.ID_ESTRELA 
			WHERE p.FACCAO = p_faccao;
	
	RETURN c_report;
END leaderReport;
