-- Views para relatorios de oficial

--View para relatório detalhado de habitantes por facção:
CREATE OR REPLACE VIEW V_HABITANTES_POR_FACCAO AS
SELECT F.NOME AS FACCAO, COUNT(DISTINCT H.PLANETA) AS TOTAL_PLANETAS, SUM(C.QTD_HABITANTES) AS TOTAL_HABITANTES
    FROM HABITACAO H
        JOIN COMUNIDADE C ON H.ESPECIE = C.ESPECIE AND H.COMUNIDADE = C.NOME
        JOIN PARTICIPA P ON C.ESPECIE = P.ESPECIE AND C.NOME = P.COMUNIDADE
        JOIN FACCAO F ON P.FACCAO = F.NOME
        JOIN DOMINANCIA D ON H.PLANETA = D.PLANETA
GROUP BY F.NOME;

--View para relatório detalhado de habitantes por espécie:
CREATE OR REPLACE VIEW V_HABITANTES_POR_ESPECIE AS
SELECT E.NOME AS ESPECIE, COUNT(DISTINCT H.PLANETA) AS TOTAL_PLANETAS, SUM(C.QTD_HABITANTES) AS TOTAL_HABITANTES
    FROM HABITACAO H
        JOIN COMUNIDADE C ON H.ESPECIE = C.ESPECIE AND H.COMUNIDADE = C.NOME
        JOIN ESPECIE E ON C.ESPECIE = E.NOME
        JOIN DOMINANCIA D ON H.PLANETA = D.PLANETA
GROUP BY E.NOME;

--View para relatório detalhado de habitantes por planeta:
CREATE OR REPLACE VIEW V_HABITANTES_POR_PLANETA AS
SELECT P.ID_ASTRO AS PLANETA, SUM(C.QTD_HABITANTES) AS TOTAL_HABITANTES
    FROM HABITACAO H
        JOIN COMUNIDADE C ON H.ESPECIE = C.ESPECIE AND H.COMUNIDADE = C.NOME
        JOIN PLANETA P ON H.PLANETA = P.ID_ASTRO
        JOIN DOMINANCIA D ON H.PLANETA = D.PLANETA
GROUP BY P.ID_ASTRO;

--View para relatório detalhado de habitantes por sistema:
CREATE OR REPLACE VIEW V_HABITANTES_POR_SISTEMA AS
SELECT S.NOME AS SISTEMA, COUNT(DISTINCT H.PLANETA) AS TOTAL_PLANETAS, SUM(C.QTD_HABITANTES) AS TOTAL_HABITANTES
    FROM HABITACAO H
        JOIN COMUNIDADE C ON H.ESPECIE = C.ESPECIE AND H.COMUNIDADE = C.NOME
        JOIN ORBITA_PLANETA OP ON H.PLANETA = OP.PLANETA
        JOIN SISTEMA S ON OP.ESTRELA = S.ESTRELA
        JOIN DOMINANCIA D ON H.PLANETA = D.PLANETA
GROUP BY S.NOME;




