/* Insertion: 500 tuples into the Nacao_Faccao Table */

INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Natus ex ab.', 'Vanguard Shadow');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Eos ab rem.', 'Eternal Storm');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Repellat hic.', 'Shadow Sentinel');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('A quam at.', 'Lunar Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Odio ut.', 'Vanguard Eclips');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('A nam ipsam.', 'Aegis Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Quasi hic fuga.', 'Iron Shadow');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Dolorum sint.', 'Eternal Titan');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Est id non.', 'Radiant Eclipse');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Sit dicta.', 'Nova Eclipse');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Et ut quia.', 'Nova Vanguard');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Minus illum a.', 'Sentinel Nebula');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Omnis sit eius.', 'Iron Lunar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ea eligendi.', 'Vanguard Nebula');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Quidem sit ad.', 'Vanguard Phoeni');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Delectus.', 'Vanguard Iron');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Culpa in omnis.', 'Radiant Radiant');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Aut debitis ea.', 'Nebula Sentinel');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Nihil qui.', 'Shadow Sentinel');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Amet in qui.', 'Solar Vanguard');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Id sint ex.', 'Shadow Vanguard');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Dolores iste.', 'Titan Eclipse');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Hic sed cumque.', 'Eternal Storm');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Et architecto.', 'Iron Aegis');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Rem sapiente.', 'Phoenix Titan');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Id ut totam.', 'Shadow Titan');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Quos ad facere.', 'Eclipse Aegis');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Hic sequi sed.', 'Radiant Radiant');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Nam minus qui.', 'Iron Vanguard');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Eos cum vero.', 'Radiant Iron');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Magnam ex qui.', 'Eternal Titan');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Nobis nostrum.', 'Shadow Shadow');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Sit beatae in.', 'Storm Lunar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ad quos et.', 'Aegis Vanguard');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Eaque optio in.', 'Eternal Vanguar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Optio a ullam.', 'Eclipse Nova');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Error dolore.', 'Titan Eclipse');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Eum quos quos.', 'Iron Shadow');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ea repellat.', 'Eclipse Solar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Similique.', 'Radiant Solar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ex nisi ab.', 'Sentinel Eterna');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Molestiae nisi.', 'Iron Phoenix');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Eum fugit fuga.', 'Eclipse Aegis');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Nemo quasi.', 'Lunar Titan');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ipsa enim.', 'Phoenix Phoenix');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ipsam vero id.', 'Sentinel Aegis');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Sed at.', 'Phoenix Phoenix');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Nam saepe vel.', 'Phoenix Solar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Amet ab qui.', 'Nebula Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Sed esse ad.', 'Vanguard Eclips');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('In quos ut.', 'Storm Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Quis culpa.', 'Phoenix Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Aut in saepe.', 'Shadow Titan');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('At rem iure.', 'Lunar Radiant');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Nemo earum.', 'Storm Phoenix');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Quasi iure a.', 'Titan Eclipse');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Omnis dolores.', 'Eternal Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Sunt a maxime.', 'Storm Aegis');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Illo fugit.', 'Shadow Eclipse');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ab vel sunt.', 'Iron Lunar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Fugiat non at.', 'Iron Sentinel');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('In ea ex.', 'Lunar Vanguard');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Nulla sit a.', 'Nova Vanguard');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Iste error in.', 'Iron Aegis');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Facilis harum.', 'Nebula Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Labore nisi ab.', 'Storm Radiant');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Eos ab quasi.', 'Phoenix Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Et et ab et.', 'Phoenix Iron');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('A ex fugit.', 'Nebula Vanguard');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Quam dicta nam.', 'Phoenix Titan');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Vero ex iure.', 'Iron Storm');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Numquam iste.', 'Eclipse Aegis');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('At a.', 'Sentinel Iron');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ex eum dolorem.', 'Eternal Titan');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Culpa cum.', 'Phoenix Vanguar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('At minus cum.', 'Eclipse Aegis');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Et animi non.', 'Radiant Eclipse');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Suscipit sed.', 'Iron Vanguard');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ipsam quia et.', 'Iron Vanguard');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ex rem quos.', 'Nova Nova');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Dolor a esse.', 'Nebula Sentinel');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ab porro odit.', 'Vanguard Sentin');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Eius enim aut.', 'Shadow Vanguard');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Id autem sit.', 'Nebula Vanguard');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Cum non quo.', 'Eclipse Nova');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ab enim aut.', 'Phoenix Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Modi a id.', 'Storm Titan');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Hic esse.', 'Nova Nova');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('A ullam.', 'Aegis Nova');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Dolores hic.', 'Storm Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('At reiciendis.', 'Aegis Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Modi amet ipsa.', 'Shadow Titan');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('At vel tenetur.', 'Iron Aegis');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Sit ut dolore.', 'Vanguard Iron');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Omnis harum.', 'Nebula Sentinel');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Rem at optio.', 'Shadow Eclipse');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Et ullam eius.', 'Sentinel Eterna');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ea nisi at.', 'Vanguard Phoeni');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('A natus esse.', 'Radiant Lunar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ea ab enim.', 'Lunar Vanguard');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Vel sunt quos.', 'Aegis Vanguard');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ut a rerum.', 'Phoenix Iron');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Sed sequi ut.', 'Eclipse Solar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('A alias iste.', 'Nebula Sentinel');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Est vitae iure.', 'Eternal Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Odit quo illum.', 'Nebula Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Eos nostrum.', 'Iron Storm');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ab eum nam.', 'Storm Radiant');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Odio quis.', 'Aegis Nova');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Porro animi.', 'Eclipse Nova');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ipsum rem et.', 'Lunar Storm');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Id nulla.', 'Vanguard Eclips');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('In vitae.', 'Iron Sentinel');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Minus iure id.', 'Aegis Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Deserunt id ex.', 'Eternal Storm');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Quaerat id vel.', 'Shadow Eclipse');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Et iure ut.', 'Eclipse Aegis');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Earum fuga.', 'Vanguard Iron');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Enim ut quo.', 'Nova Nova');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ad ullam unde.', 'Lunar Shadow');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Vero quia quod.', 'Shadow Sentinel');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Rem at ex.', 'Solar Storm');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Vitae vel.', 'Vanguard Iron');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ex esse nemo.', 'Lunar Radiant');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Eum quaerat.', 'Iron Sentinel');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Facilis dolor.', 'Nebula Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('A dolore porro.', 'Eternal Shadow');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Sint iusto at.', 'Storm Phoenix');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ea ratione ut.', 'Solar Storm');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('A ad.', 'Iron Lunar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Totam unde ad.', 'Lunar Storm');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Porro iure at.', 'Lunar Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Dolor quae.', 'Storm Aegis');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('At qui officia.', 'Aegis Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Quis enim iste.', 'Vanguard Phoeni');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Hic ea animi.', 'Radiant Lunar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Veniam ullam.', 'Aegis Iron');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Iusto modi.', 'Sentinel Iron');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Earum id vel.', 'Sentinel Iron');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Esse commodi.', 'Eclipse Aegis');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Possimus unde.', 'Storm Phoenix');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Pariatur iusto.', 'Storm Phoenix');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Assumenda in.', 'Aegis Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Quod accusamus.', 'Lunar Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('At ab a.', 'Storm Titan');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Et omnis nemo.', 'Eclipse Shadow');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Voluptatum ad.', 'Storm Titan');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Eum dolores ad.', 'Aegis Vanguard');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Optio eveniet.', 'Nova Nova');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Odio ex ut.', 'Eclipse Aegis');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Autem nemo quo.', 'Radiant Lunar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Odit libero a.', 'Vanguard Shadow');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Hic totam qui.', 'Lunar Titan');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Dolore quidem.', 'Solar Nova');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Porro amet in.', 'Eclipse Solar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Aliquid minus.', 'Titan Eclipse');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Autem a cum.', 'Vanguard Phoeni');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Sit illo.', 'Sentinel Iron');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('At ex amet.', 'Nova Nova');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ad eos at.', 'Vanguard Phoeni');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Autem nam.', 'Aegis Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('In non.', 'Nova Nova');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Nemo eum eius.', 'Shadow Sentinel');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Enim a porro.', 'Titan Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Tempore at cum.', 'Sentinel Eterna');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ipsa iure odit.', 'Phoenix Solar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Optio illo.', 'Sentinel Iron');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Quis maxime.', 'Vanguard Phoeni');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Enim vero ea.', 'Nebula Sentinel');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Nihil et fuga.', 'Nebula Sentinel');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Animi possimus.', 'Nova Solar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Nihil officiis.', 'Nebula Vanguard');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('At in quaerat.', 'Sentinel Iron');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Nam alias at.', 'Iron Vanguard');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Occaecati quos.', 'Shadow Titan');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Sint excepturi.', 'Nebula Sentinel');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Deserunt fuga.', 'Iron Lunar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Hic eos amet a.', 'Titan Solar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Impedit esse.', 'Solar Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ad ipsa unde.', 'Storm Aegis');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Eos quibusdam.', 'Shadow Nova');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Soluta illo.', 'Shadow Vanguard');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ut sed non.', 'Nebula Sentinel');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Officia natus.', 'Eclipse Nova');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Modi id.', 'Lunar Titan');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Esse in rem.', 'Phoenix Titan');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ad magni.', 'Aegis Nova');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Modi alias.', 'Eternal Shadow');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Hic quasi quam.', 'Radiant Solar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ut animi amet.', 'Nebula Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('A ea dicta.', 'Nova Nova');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Error ipsam et.', 'Phoenix Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ad id.', 'Sentinel Aegis');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Vitae ex totam.', 'Eternal Vanguar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Error eaque.', 'Iron Aegis');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Quam cum enim.', 'Vanguard Shadow');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Iure eius quas.', 'Lunar Radiant');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Nihil vel.', 'Nova Vanguard');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ullam odit.', 'Eclipse Nova');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Rem a iure.', 'Storm Phoenix');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Id nam ea.', 'Vanguard Eclips');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Saepe ab quam.', 'Solar Vanguard');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Hic sunt alias.', 'Titan Eclipse');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Voluptatum hic.', 'Sentinel Eclips');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Hic eius vitae.', 'Sentinel Lunar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Hic labore.', 'Vanguard Iron');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Sit modi autem.', 'Nova Solar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Dolor id dicta.', 'Radiant Solar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Modi nulla nam.', 'Aegis Vanguard');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Dolorum nemo.', 'Vanguard Iron');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Vel magnam.', 'Lunar Vanguard');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Culpa hic at.', 'Radiant Lunar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Dolor ad ab.', 'Solar Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Alias numquam.', 'Storm Phoenix');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Eum ex quod.', 'Solar Nova');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Id sed iure.', 'Eternal Storm');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Nam quas.', 'Iron Sentinel');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Sit id odio.', 'Radiant Lunar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Libero placeat.', 'Solar Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Sit atque.', 'Sentinel Nebula');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Amet a ipsam.', 'Nova Solar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Nobis fuga ea.', 'Vanguard Eclips');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Quia ab.', 'Phoenix Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Est nobis at.', 'Eternal Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Dicta atque.', 'Aegis Sentinel');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Earum ab vel.', 'Solar Vanguard');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ea et eum id.', 'Phoenix Titan');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Quod ab at.', 'Iron Vanguard');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Hic minima.', 'Sentinel Lunar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Quos non omnis.', 'Iron Shadow');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Nobis corporis.', 'Eternal Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Odio sapiente.', 'Aegis Vanguard');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('At veniam sunt.', 'Lunar Radiant');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Libero impedit.', 'Solar Storm');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Quis magni ex.', 'Eclipse Nova');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ut minima quam.', 'Radiant Eclipse');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('A vel ullam.', 'Vanguard Iron');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Vel optio eos.', 'Storm Lunar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Est vel ipsa.', 'Titan Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ab quos nam.', 'Vanguard Shadow');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Hic voluptates.', 'Phoenix Solar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Quo quae ea.', 'Iron Storm');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ea possimus.', 'Eclipse Nova');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ut saepe ipsa.', 'Sentinel Lunar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Nam cum et.', 'Eternal Shadow');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Porro nisi a.', 'Radiant Eclipse');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ea iusto illo.', 'Vanguard Phoeni');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Totam quod a.', 'Iron Lunar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Optio a sint.', 'Shadow Storm');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Sapiente vitae.', 'Titan Eclipse');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Natus quam ex.', 'Shadow Shadow');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Rem cum quasi.', 'Radiant Radiant');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Nesciunt sequi.', 'Radiant Radiant');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Enim at alias.', 'Eternal Radiant');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('A voluptas quo.', 'Eternal Storm');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Autem et sit.', 'Titan Solar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Esse laborum.', 'Iron Sentinel');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Cum eum non.', 'Shadow Vanguard');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Soluta ab et.', 'Solar Storm');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Non nihil cum.', 'Iron Shadow');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Tempora natus.', 'Sentinel Lunar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Velit et fuga.', 'Aegis Sentinel');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Tempora vel.', 'Radiant Solar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ipsa illo quo.', 'Storm Aegis');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ab a itaque.', 'Nova Eclipse');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Vel nemo.', 'Shadow Nova');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Dolores quos.', 'Vanguard Shadow');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('A earum quasi.', 'Lunar Storm');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Cum hic ea.', 'Eclipse Solar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ut quas quasi.', 'Shadow Storm');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Eaque repellat.', 'Sentinel Eterna');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Dicta aut ex.', 'Lunar Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Id harum nam.', 'Nova Vanguard');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Nisi a id in.', 'Lunar Titan');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('At modi ab.', 'Storm Lunar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Sit qui aut.', 'Solar Nova');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Cumque rem.', 'Eternal Storm');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Non sint at.', 'Phoenix Phoenix');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Eum ipsa quis.', 'Vanguard Phoeni');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Iure ad soluta.', 'Shadow Vanguard');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Quibusdam enim.', 'Storm Lunar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Rerum corporis.', 'Sentinel Eclips');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Vero nemo ab.', 'Shadow Shadow');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Libero ad.', 'Nova Eclipse');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('At quos nemo.', 'Eclipse Nova');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Nostrum fuga a.', 'Nebula Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Quam ut sit.', 'Vanguard Iron');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Vero nulla.', 'Storm Lunar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Dolores hic.', 'Sentinel Iron');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Aspernatur quo.', 'Vanguard Shadow');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Vitae vel.', 'Solar Vanguard');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('In modi quos.', 'Shadow Sentinel');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Rem id illo.', 'Lunar Radiant');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Quo natus nisi.', 'Lunar Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Rem voluptate.', 'Storm Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Hic quos iste.', 'Vanguard Shadow');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Iure odit vel.', 'Nova Solar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Harum ad at.', 'Phoenix Solar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ab animi.', 'Phoenix Solar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Nostrum quasi.', 'Solar Nova');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Eius iure ad.', 'Storm Titan');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Id sint velit.', 'Nebula Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Maxime magni.', 'Shadow Eclipse');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Iusto fugiat.', 'Iron Sentinel');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Similique nisi.', 'Phoenix Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Modi ipsa quam.', 'Lunar Vanguard');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ut modi ab.', 'Aegis Nova');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Sint ullam.', 'Radiant Solar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Fugit nisi non.', 'Lunar Storm');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Illum at ut.', 'Vanguard Iron');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Totam quidem.', 'Solar Vanguard');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Placeat labore.', 'Storm Aegis');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Sed quam modi.', 'Radiant Solar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ea velit eos.', 'Iron Aegis');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Nemo ad earum.', 'Vanguard Iron');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Laborum iste.', 'Aegis Iron');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Est quis.', 'Phoenix Titan');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Facilis quo.', 'Nebula Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Porro modi.', 'Shadow Eclipse');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ratione dolore.', 'Lunar Storm');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('A eius ex.', 'Iron Shadow');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ex ab voluptas.', 'Iron Vanguard');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Non eos eum.', 'Shadow Sentinel');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Debitis qui.', 'Nova Nova');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Modi at sed.', 'Radiant Radiant');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Amet non a.', 'Aegis Nova');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('In non fuga.', 'Eternal Shadow');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Laborum quo.', 'Storm Lunar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Sit quidem ad.', 'Eternal Titan');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Id odio odio.', 'Iron Aegis');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Dolorum soluta.', 'Eternal Vanguar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('A maiores ut.', 'Shadow Eclipse');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Est est fuga.', 'Vanguard Sentin');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Modi numquam.', 'Nova Eclipse');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Eius nulla qui.', 'Vanguard Phoeni');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('At neque iure.', 'Titan Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Nam dolore.', 'Eclipse Solar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('A at labore.', 'Eternal Vanguar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Sed nisi magni.', 'Aegis Vanguard');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Vero sed nulla.', 'Shadow Vanguard');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('A totam.', 'Storm Radiant');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Autem qui ea.', 'Vanguard Eclips');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ab natus culpa.', 'Iron Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Magni quae vel.', 'Sentinel Eterna');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Veritatis ad.', 'Lunar Storm');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ullam unde aut.', 'Storm Radiant');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Eos in eius.', 'Radiant Radiant');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Iste est ad.', 'Phoenix Titan');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Autem ea quos.', 'Shadow Vanguard');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Magnam nostrum.', 'Eternal Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Modi optio.', 'Shadow Sentinel');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Itaque aut in.', 'Sentinel Eclips');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Magnam atque.', 'Nebula Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Est a cum.', 'Vanguard Phoeni');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Placeat animi.', 'Iron Phoenix');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Nobis corrupti.', 'Iron Vanguard');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Eligendi dicta.', 'Eclipse Aegis');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Qui debitis a.', 'Sentinel Lunar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Iusto maiores.', 'Nova Vanguard');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ut ea nam.', 'Iron Lunar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ad unde iste.', 'Lunar Storm');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Quasi magni.', 'Shadow Eclipse');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Sunt sed culpa.', 'Shadow Storm');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Rem ullam nisi.', 'Storm Titan');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Dolores vel.', 'Lunar Aegis');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Modi at sed.', 'Vanguard Shadow');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Eum nemo.', 'Titan Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Id fuga iste.', 'Eternal Shadow');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ad ut maxime.', 'Iron Lunar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Eos autem sunt.', 'Phoenix Solar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Fuga ad fuga.', 'Iron Sentinel');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Unde aliquam.', 'Solar Storm');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Velit sint.', 'Solar Storm');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Facere animi.', 'Radiant Eclipse');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Modi iure ex.', 'Eclipse Shadow');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Dolor sint ab.', 'Sentinel Aegis');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Animi in ut.', 'Nova Vanguard');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Alias nisi.', 'Nebula Sentinel');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Vero nam ut.', 'Shadow Shadow');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Quam sint aut.', 'Eternal Shadow');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Vel eveniet.', 'Shadow Titan');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ducimus quod.', 'Radiant Lunar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Non sint modi.', 'Iron Lunar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Modi cum eius.', 'Aegis Nova');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Quam hic.', 'Sentinel Nebula');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Nisi ipsa hic.', 'Aegis Nova');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Unde a quam.', 'Eclipse Shadow');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Quis amet ad.', 'Lunar Titan');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Omnis mollitia.', 'Shadow Shadow');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Aut magni eum.', 'Aegis Iron');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ab modi quas.', 'Sentinel Iron');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Provident eos.', 'Eternal Radiant');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Qui deleniti.', 'Nebula Sentinel');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Corrupti minus.', 'Nova Eclipse');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Natus rem ab.', 'Eternal Storm');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Sed ex iure.', 'Storm Aegis');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ea ipsum eum.', 'Shadow Sentinel');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Dolores fuga.', 'Vanguard Shadow');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ipsa eum unde.', 'Eternal Radiant');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ipsam illo.', 'Shadow Eclipse');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Rerum cum fuga.', 'Phoenix Phoenix');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Quas odit sit.', 'Solar Nova');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ex ex nobis.', 'Shadow Shadow');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Vel ut eius.', 'Storm Aegis');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Rem voluptas.', 'Storm Radiant');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Quam delectus.', 'Eternal Titan');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Rem unde dolor.', 'Phoenix Vanguar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Qui eligendi.', 'Eternal Radiant');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ad nihil et.', 'Eternal Radiant');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Sunt modi a.', 'Radiant Solar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Eius id.', 'Iron Shadow');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Quis optio hic.', 'Lunar Storm');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Labore a ad.', 'Lunar Aegis');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Iure cumque.', 'Iron Aegis');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Id eius ipsam.', 'Iron Aegis');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Et iure ipsa.', 'Solar Storm');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Qui minima.', 'Storm Radiant');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Quasi deserunt.', 'Iron Vanguard');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Facere unde ex.', 'Iron Sentinel');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Magni ad non.', 'Vanguard Nebula');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Et maxime a.', 'Storm Titan');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ea modi quia.', 'Storm Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Sed ipsum enim.', 'Radiant Solar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Odit in sit.', 'Phoenix Vanguar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Dolore autem.', 'Nova Eclipse');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Nihil ea cum.', 'Eclipse Shadow');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Aut tenetur a.', 'Radiant Solar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('A magni iure.', 'Lunar Storm');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Quaerat optio.', 'Titan Eclipse');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Pariatur rem.', 'Vanguard Sentin');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('In magni quod.', 'Phoenix Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Dolores labore.', 'Nova Eclipse');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Quod odit.', 'Aegis Sentinel');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Alias eum quos.', 'Eclipse Solar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Aut vero ex.', 'Lunar Aegis');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Vero id aut.', 'Eternal Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Quos soluta.', 'Storm Radiant');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Facere animi.', 'Phoenix Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Id in modi.', 'Radiant Iron');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ea doloribus.', 'Nebula Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Dolor ex eum.', 'Nebula Vanguard');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Hic autem sit.', 'Shadow Eclipse');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Rem hic ex.', 'Solar Storm');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Est id qui.', 'Aegis Vanguard');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Minus nihil.', 'Nova Nova');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Quia ut atque.', 'Lunar Shadow');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Sint a.', 'Eclipse Solar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Earum minima.', 'Vanguard Shadow');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Odit eius.', 'Shadow Sentinel');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Sed voluptatem.', 'Vanguard Shadow');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Officiis alias.', 'Sentinel Aegis');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Labore ea unde.', 'Storm Phoenix');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Magnam aut est.', 'Titan Eclipse');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ea eius nam.', 'Eternal Storm');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Sunt sint.', 'Titan Eclipse');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ab alias sit.', 'Radiant Radiant');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('At nihil amet.', 'Phoenix Titan');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Id est nemo.', 'Eclipse Shadow');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('At magnam ad.', 'Eternal Titan');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ex beatae quo.', 'Vanguard Eclips');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Cum eum rem.', 'Phoenix Iron');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ipsam ab.', 'Nebula Sentinel');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Velit quis.', 'Eclipse Shadow');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('A odit at.', 'Phoenix Iron');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('A enim in.', 'Vanguard Nebula');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Et a dolor.', 'Phoenix Phoenix');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Et eius id.', 'Shadow Nova');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Minus veniam.', 'Sentinel Eclips');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Sed debitis.', 'Radiant Iron');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Eum ut magni.', 'Vanguard Eclips');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Fugiat vel eum.', 'Nova Eclipse');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Iusto in omnis.', 'Vanguard Iron');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Id iure vero.', 'Storm Titan');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Esse aliquid.', 'Solar Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Sit impedit a.', 'Shadow Sentinel');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Delectus rem.', 'Aegis Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Quas hic ea.', 'Nova Eclipse');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Soluta ea cum.', 'Eternal Shadow');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Quod sit hic.', 'Eternal Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Quod ipsa id.', 'Vanguard Phoeni');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Earum nam ea.', 'Storm Lunar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Veritatis ex.', 'Iron Storm');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ipsa rem ad.', 'Lunar Aegis');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Vero sed eius.', 'Storm Aegis');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Hic nemo nobis.', 'Phoenix Iron');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Nemo maxime.', 'Sentinel Nebula');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Aut ex eos.', 'Shadow Titan');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Quis fuga quam.', 'Iron Sentinel');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Eum atque esse.', 'Iron Phoenix');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Quod odio ad.', 'Lunar Storm');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Nostrum enim a.', 'Eclipse Solar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Saepe quod et.', 'Aegis Iron');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Hic harum qui.', 'Nova Nova');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('In ipsum eos.', 'Eclipse Aegis');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ea nobis ad.', 'Phoenix Eternal');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Asperiores nam.', 'Eclipse Nova');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Sint quis illo.', 'Iron Lunar');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Ea fugit.', 'Radiant Radiant');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Nemo hic in.', 'Aegis Nova');
INSERT INTO NACAO_FACCAO (NACAO, FACCAO) VALUES ('Nihil maiores.', 'Phoenix Vanguar');