set serveroutput on;

/* Teste: Log */
BEGIN
    PG_Users.set_user_id('117.586.170-10');

    -- TESTE EM FACCAO
    INSERT INTO NACAO VALUES('Imperio Dalek', 1, 'Poder obscuro');
    UPDATE NACAO N SET NOME = 'Gallyos' WHERE N.FEDERACAO = 'Poder obscuro';
    DELETE FROM NACAO N WHERE N.NOME = 'Gallyos';
    
    -- TESTE EM NACAO
    INSERT INTO FACCAO VALUES('Senhor do tempo', '117.586.170-10', 'PROGRESSISTA', 1);
    UPDATE FACCAO F SET NOME = 'Daleks' WHERE F.NOME = 'Senhor do tempo';
    DELETE FROM FACCAO F WHERE F.NOME = 'Senhor do tempo';
    
    -- TESTE EM ESTRELA
    INSERT INTO estrela VALUES ('GJ 9393', 'TESTE_LOG_1','M2V',0.0231206479017559,-16.253483,-0.777026,14.173909);
    UPDATE ESTRELA E SET NOME = 'TESTE_LOG_2' WHERE E.NOME = 'TESTE_LOG_1';
    --DELETE FROM ESTRELA E WHERE E.NOME = 'TESTE_LOG_2';
    
    -- TESTE PLANETA
    INSERT INTO planeta VALUES ('TESTE_LOG_1', NULL,0.273,'Confirmed');
    UPDATE PLANETA P SET ID_ASTRO = 'TESTE_LOG_1' WHERE P.ID_ASTRO = 'TESTE_LOG_1';
    DELETE FROM PLANETA P WHERE P.ID_ASTRO = 'TESTE_LOG_2';
    
    -- TESTE SISTEMA
    INSERT INTO SISTEMA VALUES ('GJ 9393', 'TESTE_LOG_1');
    UPDATE SISTEMA S SET NOME = 'TESTE_LOG_2' WHERE S.NOME = 'TESTE_LOG_1';
    DELETE FROM SISTEMA S WHERE S.NOME = 'TESTE_LOG_2';
    
    ROLLBACK;
    
    EXCEPTION
        WHEN OTHERS THEN 
            dbms_output.put_line(SQLERRM);
END;